-- CCR-015: ประเด็นท้าทาย gains a subject, and two unscored form fields.
--
-- Hand-written, NOT generated by `prisma migrate dev`, for the reason recorded in
-- 20260718220000_scan_status_unscanned: Prisma's introspection cannot see the
-- STORED GENERATED columns (evaluation_cycle.pa_uk_key,
-- round_result.passed_individual_threshold) or the trigger-maintained
-- evidence_indicator_mapping.active_uk_key, so a generated migration would
-- quietly emit statements dropping their generation and uniqueness.
--
-- `title` is NOT NULL with no default and no backfill. That is safe here and
-- only here: nothing in the codebase could create an agreement_challenge row
-- before this migration (PerformanceAgreement and AgreementChallenge had zero
-- references in apps/ and packages/ — that absence IS SEIP-BLOCK-002), so the
-- table is empty in every environment. Verified against the dev database before
-- writing this. A later migration adding a required column to this table will
-- NOT have that luxury and will need a default or a backfill.

ALTER TABLE `agreement_challenge`
  ADD COLUMN `title` VARCHAR(500) NOT NULL,
  ADD COLUMN `target_group` VARCHAR(500) NULL,
  ADD COLUMN `period_note` VARCHAR(500) NULL;

-- Deliberately NOT done: a CHECK or trigger forcing exactly one challenge row per
-- agreement.
--
-- The `agreement_challenge_agreement_id_indicator_id_key` unique index already
-- makes "one row per (agreement, indicator)" a database fact, and the application
-- always files against the framework's single วิธีดำเนินการ indicator (T-C.1 /
-- A-C.1), so one-per-agreement follows. Encoding "exactly one" in the schema would
-- additionally forbid the legitimate intermediate state this contract allows on
-- purpose: an agreement created in `draft` with its challenge still to be written
-- (openapi AgreementCreate.challenge is optional; submitAgreement is what requires
-- it, via AGR-002).
