-- CCR-012: ScanStatus gains `unscanned` — "processed, but no scanner ran".
--
-- Hand-written, NOT generated by `prisma migrate dev`. Prisma's introspection
-- cannot see the STORED GENERATED columns (evaluation_cycle.pa_uk_key,
-- round_result.passed_individual_threshold) or the trigger-maintained
-- evidence_indicator_mapping.active_uk_key, so a generated migration would
-- quietly emit statements dropping their generation/uniqueness. Enum widening
-- is a one-line ALTER; writing it by hand is cheaper than repairing that.
--
-- Widening an ENUM in place is non-destructive: every existing value keeps its
-- meaning, no row is rewritten to a new state by this migration. Rows currently
-- reading 'clean' were written by the removed filename stub and are NOT
-- retroactively corrected here — see the note at the bottom.

ALTER TABLE `evidence_file`
  MODIFY `scan_status` ENUM('pending', 'clean', 'unscanned', 'blocked') NOT NULL DEFAULT 'pending';

-- Deliberately NOT done: `UPDATE evidence_file SET scan_status = 'unscanned'
-- WHERE scan_status = 'clean'`.
--
-- Every 'clean' row in an existing database was produced by the stub and is
-- therefore unverified, so rewriting them would be the more truthful state. It is
-- left out because this migration cannot distinguish those rows from ones a real
-- scanner might have cleared after the scanner is wired in, and a destructive
-- backfill belongs in a reviewed data task, not a schema migration. Any
-- deployment predating CCR-012 should run that backfill once, before trusting the
-- badge. Fresh databases are unaffected.
