-- ADR-0009 follow-up: `scanned_at` — the receipt for a real scan.
--
-- Hand-written, NOT generated by `prisma migrate dev`, for the reason recorded in
-- 20260718220000: Prisma's introspection cannot see the STORED GENERATED columns
-- (evaluation_cycle.pa_uk_key, round_result.passed_individual_threshold) or the
-- trigger-maintained evidence_indicator_mapping.active_uk_key, so a generated
-- migration quietly emits statements dropping their generation and uniqueness.
--
-- ## What this column fixes
--
-- `scan_status` alone cannot answer "was this file ever actually scanned?".
-- 20260718220000 hit this exactly, and said so in its own closing note: it
-- declined to rewrite `clean` → `unscanned` because it "cannot distinguish those
-- rows from ones a real scanner might have cleared". That distinction is a fact
-- about history, so it needs somewhere to live. Here it is.
--
-- `scanned_at IS NULL` means no scanner has ever read the bytes. That is true of:
--   * every row the deleted CCR-012 filename stub wrote as `clean` (unverified,
--     downloadable, and the UI badge says ปลอดภัย over them)
--   * `unscanned` rows from any SCAN_PROVIDER=none period
--   * files blocked on size or size-mismatch — refused without being read, so
--     "could not be checked" stays re-checkable rather than curdling into a
--     permanent verdict
--
-- ## Deliberately no backfill
--
-- Every existing row gets NULL, and NULL is the truth for every one of them: this
-- schema has never had a real scanner behind it. Nothing here rewrites
-- `scan_status`. The correction is a data operation an operator runs and watches
-- (`npm run rescan:files`), which re-derives each verdict from the actual bytes
-- rather than guessing at one in DDL. A destructive backfill still belongs in a
-- reviewed data task, not a schema migration.

ALTER TABLE `evidence_file`
  ADD COLUMN `scanned_at` DATETIME(3) NULL AFTER `scan_status`;

-- Supports the sweep's selection query (`scanned_at IS NULL`, and later
-- `scanned_at < <signature date>`), oldest first.
CREATE INDEX `evidence_file_scanned_at_idx` ON `evidence_file`(`scanned_at`);
