-- CCR-014: onboarding — invite tokens on user_account.
--
-- Hand-written, NOT generated by `prisma migrate dev`, for the reason recorded in
-- 20260718220000_scan_status_unscanned: Prisma's introspection cannot see the
-- STORED GENERATED columns (evaluation_cycle.pa_uk_key,
-- round_result.passed_individual_threshold) or the trigger-maintained
-- evidence_indicator_mapping.active_uk_key, so a generated migration would
-- quietly emit statements dropping their generation and uniqueness. This change
-- is two nullable columns; writing them by hand is cheaper than repairing that.
--
-- Purely additive. Both columns are NULL for every existing row, which is the
-- correct state: an account that already has a password is not awaiting an
-- invite. No row is rewritten, no constraint is tightened, nothing is backfilled.

ALTER TABLE `user_account`
  ADD COLUMN `invite_token_hash` VARCHAR(191) NULL,
  ADD COLUMN `invite_expires_at` DATETIME(3) NULL;

-- Unique so a token hash cannot address two accounts. Nullable + UNIQUE is the
-- shape we want in MySQL: InnoDB permits unlimited NULLs in a unique index, so
-- every already-accepted account (hash NULL) coexists freely, while any live
-- token resolves to exactly one row.
CREATE UNIQUE INDEX `user_account_invite_token_hash_key`
  ON `user_account`(`invite_token_hash`);

-- Deliberately NOT done: a CHECK tying invite_token_hash to status='invited'.
--
-- The intended invariant is "a non-null hash implies the account has not yet
-- accepted", and the accept path enforces it by clearing the hash in the same
-- transaction that writes password_hash. It is left out of the schema because
-- the reverse is not true — an `invited` account whose token has expired
-- legitimately keeps a stale hash until re-invited, and an admin re-inviting an
-- `active` account (password reset by another name, deferred in CCR-014) would
-- also break the CHECK. Encoding a rule the product does not actually hold would
-- surface as a 500 on a legitimate path.
