/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a token pair */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token into a new token pair (CCR-008, SEC-AUTH-2)
         * @description The presented refresh token is the credential (no bearer header). On
         *     success the old token is revoked and a NEW pair is returned — the client
         *     must replace both stored tokens. Presenting an already-rotated (revoked)
         *     token is treated as a theft signal: every live token for that account is
         *     revoked and the request fails AUTH-001.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke refresh token(s) server-side (CCR-008, SEC-AUTH-2)
         * @description With a `refresh_token` in the body, revokes that token (this session).
         *     Without one, revokes every live refresh token for the caller (logout
         *     everywhere). The short-lived access token is not blacklisted — it ages
         *     out within ACCESS_TOKEN_TTL_SECONDS.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user identity, memberships and roles */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frameworks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List framework versions (ว9/ว10 revisions) */
        get: operations["listFrameworks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/frameworks/{frameworkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One framework with its domain→indicator tree
         * @description Per-rank rubric level descriptions are large; request them explicitly with `include=levels`.
         */
        get: operations["getFramework"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence categories with upload validation metadata */
        get: operations["listEvidenceCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List evaluation cycles of the caller's school */
        get: operations["listCycles"];
        put?: never;
        /** Create an evaluation cycle (school admin) */
        post: operations["createCycle"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cycles/{cycleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One cycle with its rounds */
        get: operations["getCycle"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update cycle status/title/dates (school admin) */
        patch: operations["updateCycle"];
        trace?: never;
    };
    "/cycles/{cycleId}/rounds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a round to a cycle (rounds are 1..n, data-driven) */
        post: operations["createRound"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rounds/{roundId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update round period or transition its status
         * @description Legal transitions planned→open→scoring→closed (CYCLE-001). Closing freezes all scores (SCORE-002).
         */
        patch: operations["updateRound"];
        trace?: never;
    };
    "/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List evidence (school-scoped; teachers see their own by default) */
        get: operations["listEvidence"];
        put?: never;
        /** Create a logical evidence item (metadata only; files attach via two-phase upload) */
        post: operations["createEvidence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{evidenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evidence detail with files and mappings */
        get: operations["getEvidence"];
        put?: never;
        post?: never;
        /** Soft-delete evidence (audited; storage GC is async policy) */
        delete: operations["deleteEvidence"];
        options?: never;
        head?: never;
        /** Update evidence metadata (owner or school admin) */
        patch: operations["updateEvidence"];
        trace?: never;
    };
    "/evidence/{evidenceId}/files/initiate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Phase 1: validate metadata and obtain an upload target
         * @description Validates content type / size / (video) duration against the evidence category
         *     (UPL-001..003) **before** bytes move. Returns a provider-agnostic upload target
         *     (presigned URL or equivalent). Client uploads bytes directly to storage,
         *     then calls the complete endpoint.
         */
        post: operations["initiateFileUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{evidenceId}/files/{fileId}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Phase 2: confirm bytes uploaded; register file and enqueue virus scan
         * @description Emits `evidence.file.registered`; scan result arrives via `evidence.file.scan_completed` (events.yaml). File is served when scan_status is clean or unscanned; blocked/pending return UPL-006.
         */
        post: operations["completeFileUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{evidenceId}/files/{fileId}/download-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Issue a short-lived download URL for one clean evidence file
         * @description Lazy download (CCR-010 / cleanup H2). Call only when the user intends to
         *     download — `getEvidence` and `completeFileUpload` never presign object
         *     storage. Requires `scan_status` to be `clean` or `unscanned` (CCR-012 —
         *     unscanned means no scanner ran, which is disclosed rather than blocked);
         *     `pending`/`blocked` return UPL-006. Same tenancy grants as `getEvidence`.
         *     Never returns `storage_uri`.
         */
        get: operations["getEvidenceFileDownloadUrl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{evidenceId}/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mappings of one evidence item */
        get: operations["listEvidenceMappings"];
        put?: never;
        /** Map evidence to an indicator (human proposal; status=suggested until confirmed) */
        post: operations["createMapping"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/evidence/{evidenceId}/mappings/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Suggest indicator mappings for evidence (local heuristic; ADR-0007)
         * @description Creates zero or more mappings with mapping_source=ai_suggested and
         *     status=suggested. Never auto-confirms. On-prem only — no foreign LLM
         *     while ADR-0005 holds. Empty suggestions return 200 with items=[].
         */
        post: operations["suggestMappings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mapping review queue (filter by indicator, cycle, status) */
        get: operations["listMappings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/mappings/{mappingId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Confirm, reject, or revoke a mapping (governance action, audited) */
        patch: operations["actOnMapping"];
        trace?: never;
    };
    "/rounds/{roundId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluation assignments in a round */
        get: operations["listAssignments"];
        put?: never;
        /**
         * Create an assignment with its 3-member committee
         * @description Committee must be exactly 3 (SCORE-001) — chair + 2 members, per ว9/ว10.
         */
        post: operations["createAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/{assignmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Assignment detail (committee, workload gate, scoring progress) */
        get: operations["getAssignment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/{assignmentId}/my-scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Submit or replace the calling evaluator's full score set (idempotent upsert)
         * @description Per-evaluator grain (ADR-0003): each of the 3 committee members submits their own
         *     complete set — all scored standard indicators + challenge items (SCORE-005) with
         *     rubric levels 1..4 (SCORE-003). Requires committee membership (PERM-003),
         *     a declared workload gate (SCORE-004), and an open/scoring round (SCORE-002).
         *     Rollup (part1/part2/total %, ≥70% flag) is computed server-side per evaluator.
         */
        put: operations["submitMyScores"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assignments/{assignmentId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-evaluator rollups and overall pass verdict
         * @description Overall pass = workload gate met AND every evaluator's total ≥ 70%.
         */
        get: operations["getAssignmentResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List reports for the current school (filter by cycle/subject/status) */
        get: operations["listReports"];
        put?: never;
        /**
         * Request generation of a structured PA report (async worker fills payload)
         * @description Creates a draft Report row and enqueues report.generate. Clients consume
         *     structured payload + section_refs; PDF is available via getReportPdf once
         *     generation completes. Section refs may only cite confirmed mappings.
         */
        post: operations["createReport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report detail including payload and section refs */
        get: operations["getReport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{reportId}/pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download PA form PDF generated from report payload
         * @description Returns application/pdf built on demand from structured payload + section_refs.
         *     Requires generation complete (not draft / generation_status=pending) — else RPT-002.
         *     Layout is SEIP structure-faithful PA1/PA2/PA3 form, not the Protected Artifact plate.
         */
        get: operations["getReportPdf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description Stable code from error-codes.yaml */
            code: string;
            message: string;
            details?: {
                field: string;
                issue: string;
            }[];
            /** Format: uuid */
            request_id?: string;
        };
        /** @enum {string} */
        RoleFamily: "teacher" | "administrator";
        /** @enum {string} */
        Role: "teacher" | "director" | "deputy" | "evaluator" | "school_admin" | "area_admin";
        /** @enum {string} */
        EvaluationKind: "pa" | "dpa";
        /** @enum {string} */
        CycleStatus: "planned" | "open" | "closed";
        /** @enum {string} */
        RoundStatus: "planned" | "open" | "scoring" | "closed";
        /** @enum {string} */
        EvidenceStatus: "draft" | "active" | "archived" | "rejected";
        /** @enum {string} */
        MappingStatus: "suggested" | "confirmed" | "rejected" | "revoked";
        /**
         * @description ai_suggested set only by suggestMappings (ADR-0007 local_heuristic)
         * @enum {string}
         */
        MappingSource: "human" | "ai_suggested";
        /** @enum {string} */
        ReportStatus: "draft" | "pending_approval" | "approved" | "issued" | "superseded";
        /**
         * @description PA form family × ส/บส variant (layout deferred; code selects payload shape)
         * @enum {string}
         */
        ReportTemplateCode: "PA1_s" | "PA1_bs" | "PA2_s" | "PA2_bs" | "PA3_s" | "PA3_bs";
        /**
         * @description `pending` — queued, the worker has not processed the file yet.
         *     `clean` — a scanner ran and found nothing.
         *     `unscanned` — the file was processed but NO scanner ran, so the platform
         *     makes no claim about its contents (CCR-012). This is the state on any
         *     deployment without a malware scanner wired in. It is served like `clean`
         *     — the distinction is disclosure, not restriction — and clients are
         *     expected to surface it so nobody reads silence as a clean bill of health.
         *     `blocked` — quarantined: a scanner rejected it, or the stored object did
         *     not match the declared byte_size. Never served (UPL-006).
         * @enum {string}
         */
        ScanStatus: "pending" | "clean" | "unscanned" | "blocked";
        RubricLevel: number;
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        TokenPair: {
            access_token: string;
            refresh_token: string;
            /** @description Access token TTL seconds */
            expires_in: number;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        LogoutRequest: {
            /** @description Revoke only this token (this session). Omit to revoke all the caller's tokens. */
            refresh_token?: string;
        };
        CurrentUser: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            display_name: string;
            /** @description Present when the user is school personnel (evaluatee-capable). Null otherwise. (CCR-002) */
            personnel?: null | {
                /** Format: uuid */
                id: string;
                position_role: components["schemas"]["RoleFamily"];
                /**
                 * @description วิทยฐานะ tier code — selects IndicatorLevel.expected_practice_th
                 * @example teacher_kru
                 * @example teacher_chamnankan
                 */
                rank_level_code: string;
            };
            memberships: {
                role: components["schemas"]["Role"];
                /** @enum {string} */
                membership_scope: "school" | "area";
                /** Format: uuid */
                school_id?: string | null;
                /** Format: uuid */
                area_id?: string | null;
            }[];
        };
        Framework: {
            /** Format: uuid */
            id: string;
            /** @example v9-2564-teacher */
            code: string;
            role_family: components["schemas"]["RoleFamily"];
            /** @example ศธ 0206.3/ว 9 ลว. 20 พ.ค. 2564 */
            legal_ref: string;
            /** @example 2564 */
            revision_year: number;
            /** @enum {string} */
            status: "active" | "superseded" | "draft";
        };
        FrameworkDetail: components["schemas"]["Framework"] & {
            domains: components["schemas"]["Domain"][];
            /** @description Framework data (e.g. part1=60, part2=40, challenge method=20) */
            score_weights: {
                /** @example part1_total */
                weight_key: string;
                weight_value: number;
            }[];
        };
        Domain: {
            /** Format: uuid */
            id: string;
            /** @example T-D1 */
            code: string;
            /** @example ด้านการจัดการเรียนรู้ */
            name_th: string;
            sort_order: number;
            /** @enum {string} */
            part: "standards" | "challenge";
            indicators: components["schemas"]["Indicator"][];
        };
        Indicator: {
            /** Format: uuid */
            id: string;
            /** @example T-1.1 */
            code: string;
            name_th: string;
            sort_order: number;
            is_scored: boolean;
            /** @enum {string} */
            indicator_kind: "standard" | "challenge" | "workload_gate";
            /** @description Present only when requested with include=levels */
            levels?: components["schemas"]["IndicatorLevel"][];
        };
        IndicatorLevel: {
            /** @example teacher_kru */
            rank_level_code: string;
            rubric_level: components["schemas"]["RubricLevel"];
            expected_practice_th: string;
        };
        EvidenceCategory: {
            /** Format: uuid */
            id: string;
            /** @example problem_inspiration_video_mp4 */
            code: string;
            label_th: string;
            allowed_mime_types: string[];
            max_byte_size?: number | null;
            /** @description e.g. 600 for the problem/inspiration video (ว9) */
            max_duration_seconds?: number | null;
            required_for_dpa: boolean;
        };
        Cycle: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            school_id: string;
            /** Format: uuid */
            framework_version_id: string;
            /** @example 2569 */
            fiscal_year: number;
            evaluation_kind: components["schemas"]["EvaluationKind"];
            title: string;
            status: components["schemas"]["CycleStatus"];
            /** Format: date */
            starts_on: string;
            /** Format: date */
            ends_on: string;
        };
        CycleCreate: {
            /** Format: uuid */
            framework_version_id: string;
            fiscal_year: number;
            evaluation_kind: components["schemas"]["EvaluationKind"];
            title: string;
            /** Format: date */
            starts_on: string;
            /** Format: date */
            ends_on: string;
        };
        /** @description At least one property required */
        CyclePatch: {
            title?: string;
            status?: components["schemas"]["CycleStatus"];
            /** Format: date */
            starts_on?: string;
            /** Format: date */
            ends_on?: string;
        };
        CycleDetail: components["schemas"]["Cycle"] & {
            rounds: components["schemas"]["Round"][];
        };
        Round: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            cycle_id: string;
            round_number: number;
            /** @example salary_round_1 */
            purpose: string;
            /** Format: date */
            period_start: string;
            /** Format: date */
            period_end: string;
            status: components["schemas"]["RoundStatus"];
        };
        RoundCreate: {
            round_number: number;
            purpose: string;
            /** Format: date */
            period_start: string;
            /** Format: date */
            period_end: string;
        };
        RoundPatch: {
            purpose?: string;
            /** Format: date */
            period_start?: string;
            /** Format: date */
            period_end?: string;
            status?: components["schemas"]["RoundStatus"];
        };
        /**
         * @description Lifecycle (CCR-002): created as `draft`; the server promotes to `active` when the
         *     first file upload completes successfully. Clients never set draft→active directly;
         *     EvidencePatch.status is for archive/reject transitions only.
         */
        Evidence: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            school_id: string;
            /** Format: uuid */
            owner_personnel_id: string;
            /** Format: uuid */
            uploaded_by_user_id?: string;
            /** Format: uuid */
            category_id: string;
            title: string;
            description?: string | null;
            status: components["schemas"]["EvidenceStatus"];
            /** Format: date-time */
            captured_at?: string | null;
            /** Format: date-time */
            created_at: string;
            /**
             * @description Aggregate of attached files (CCR-009). null when there are no files.
             *     Worst-of order: pending > blocked > unscanned > clean. Present on list and detail so
             *     clients never need N+1 detail fetches for list badges.
             */
            scan_status?: null | components["schemas"]["ScanStatus"];
        };
        EvidenceCreate: {
            /**
             * Format: uuid
             * @description Defaults to the caller's own personnel profile; admins may set another owner
             */
            owner_personnel_id?: string | null;
            /** Format: uuid */
            category_id: string;
            title: string;
            description?: string | null;
            /** Format: date-time */
            captured_at?: string | null;
        };
        EvidencePatch: {
            title?: string;
            description?: string | null;
            status?: components["schemas"]["EvidenceStatus"];
            /** Format: date-time */
            captured_at?: string | null;
        };
        EvidenceDetail: components["schemas"]["Evidence"] & {
            files: components["schemas"]["EvidenceFile"][];
            mappings: components["schemas"]["Mapping"][];
        };
        EvidenceFile: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            evidence_id: string;
            content_type: string;
            byte_size: number;
            checksum_sha256?: string;
            duration_seconds?: number | null;
            original_filename?: string;
            scan_status: components["schemas"]["ScanStatus"];
            /**
             * @description Always null on EvidenceFile payloads (CCR-010). Clients obtain a
             *     short-lived URL via getEvidenceFileDownloadUrl when scan_status=clean
             *     (UPL-006). Field retained for schema stability.
             */
            download_url?: string | null;
            /** Format: date-time */
            uploaded_at: string;
        };
        FileDownloadUrl: {
            /**
             * Format: uri
             * @description Short-lived presigned GET; never reuse after expires_at
             */
            download_url: string;
            /** Format: date-time */
            expires_at: string;
        };
        FileUploadInitiate: {
            content_type: string;
            byte_size: number;
            checksum_sha256: string;
            original_filename: string;
            /**
             * @description Video categories: send when the client can read it (enables fail-fast UPL-003
             *     before bytes move); null is always allowed — the server-side probe after upload
             *     is the authoritative UPL-003 enforcement (CCR-002).
             */
            duration_seconds?: number | null;
        };
        FileUploadTarget: {
            /** Format: uuid */
            file_id: string;
            /** @description Provider-agnostic presigned target */
            upload_url: string;
            /** @enum {string} */
            method: "PUT" | "POST";
            headers?: {
                [key: string]: string;
            };
            /** Format: date-time */
            expires_at: string;
        };
        /**
         * @description Widened by CCR-004 (v2.0.0 — BREAKING, see the file header note on why a
         *     major bump was correct here): the original v1.0.0 shape assumed a
         *     server-side upload session remembering initiate's declared metadata, which
         *     this API doesn't implement. The client resends content_type/byte_size/
         *     original_filename/duration_seconds alongside the checksum so complete can
         *     rebuild the same storage key and re-validate. See docs/reviews/CCR-004-*.md
         *     for the accepted limitation this carries (no server-side re-read of the
         *     actual uploaded bytes yet).
         */
        FileUploadComplete: {
            /** @description Must equal the initiate value (UPL-005) */
            checksum_sha256: string;
            /** @description Must equal the initiate value — re-validated against the category (CCR-004) */
            content_type: string;
            byte_size: number;
            original_filename: string;
            /** @description Same nullable/probe-authoritative semantics as FileUploadInitiate (CCR-002) */
            duration_seconds?: number | null;
        };
        Mapping: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            evidence_id: string;
            /** Format: uuid */
            indicator_id: string;
            /** Format: uuid */
            cycle_id?: string | null;
            mapping_source: components["schemas"]["MappingSource"];
            status: components["schemas"]["MappingStatus"];
            rationale?: string | null;
            /** Format: uuid */
            mapped_by_user_id?: string;
            /** Format: uuid */
            confirmed_by_user_id?: string | null;
            /** Format: date-time */
            mapped_at: string;
            /** Format: date-time */
            confirmed_at?: string | null;
        };
        MappingCreate: {
            /** Format: uuid */
            indicator_id: string;
            /** Format: uuid */
            cycle_id?: string | null;
            rationale?: string | null;
        };
        /** @description Optional filters for local_heuristic suggest (ADR-0007) */
        MappingSuggestRequest: {
            /**
             * Format: uuid
             * @description Attach suggested mappings to this cycle when set
             */
            cycle_id?: string | null;
            /**
             * Format: uuid
             * @description Limit candidate indicators to this framework; defaults to cycle's framework when cycle_id set
             */
            framework_version_id?: string | null;
            /** @default 5 */
            max_suggestions: number;
        };
        MappingSuggestResult: {
            /**
             * @description Always local_heuristic under ADR-0007
             * @enum {string}
             */
            provider: "local_heuristic";
            items: components["schemas"]["Mapping"][];
            /** @description Count of candidate indicators skipped because an active mapping already exists */
            skipped_active?: number;
        };
        MappingAction: {
            /** @enum {string} */
            action: "confirm" | "reject" | "revoke";
            rationale?: string | null;
        };
        Assignment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            round_id: string;
            /** Format: uuid */
            evaluatee_personnel_id: string;
            /** Format: uuid */
            agreement_id?: string | null;
            /** @enum {string} */
            status: "pending" | "in_progress" | "completed" | "void";
            committee: components["schemas"]["CommitteeMember"][];
        };
        CommitteeMember: {
            /** Format: uuid */
            evaluator_user_id: string;
            /** @enum {string} */
            committee_role: "chair" | "member";
            seat_number: number;
        };
        AssignmentCreate: {
            /** Format: uuid */
            evaluatee_personnel_id: string;
            /** Format: uuid */
            agreement_id?: string | null;
            /** @description Exactly 3 per ว9/ว10 (SCORE-001) — one chair, two members */
            committee: components["schemas"]["CommitteeMember"][];
        };
        AssignmentDetail: components["schemas"]["Assignment"] & {
            workload_gate_declared: boolean;
            workload_met?: boolean | null;
            /**
             * @description Scoring progress of the calling evaluator
             * @enum {string}
             */
            my_submission_state: "not_member" | "not_submitted" | "submitted";
            /**
             * Format: uuid
             * @description Framework pinned by the assignment's cycle (CCR-009). Clients use this
             *     to load taxonomy for scoring — no graph walk over cycles/rounds.
             */
            framework_version_id: string;
            /**
             * @description วิทยฐานะ of the person being evaluated (CCR-013). IndicatorLevel rows
             *     are keyed by (rank_level_code, rubric_level), so without this a client
             *     cannot tell which rank's expected-practice text applies and is forced
             *     to invent generic rubric labels — which is what apps/web did. There is
             *     no personnel lookup operation, so this cannot be resolved client-side.
             * @example apply_adapt
             */
            evaluatee_rank_level_code: string;
        };
        ScoreSubmission: {
            /** @description Chair may declare the workload gate in the same call (SCORE-004) */
            workload_met?: boolean | null;
            /** @description Complete set — every scored indicator (standard + challenge) of the framework (SCORE-005) */
            indicator_scores: {
                /** Format: uuid */
                indicator_id: string;
                rubric_level: components["schemas"]["RubricLevel"];
                comment?: string | null;
            }[];
        };
        EvaluatorResult: {
            /** Format: uuid */
            assignment_id: string;
            /** Format: uuid */
            evaluator_user_id: string;
            /** @description Weighted per framework data (e.g. /60) */
            part1_percent: number;
            part2_percent: number;
            total_percent: number;
            /** @description total_percent >= 70 */
            passed_individual_threshold: boolean;
            /** Format: date-time */
            computed_at?: string;
        };
        AssignmentResults: {
            /** Format: uuid */
            assignment_id: string;
            workload_gate_met: boolean | null;
            evaluator_results: components["schemas"]["EvaluatorResult"][];
            /** @description All 3 evaluators submitted */
            complete: boolean;
            /** @description Null until complete; true iff workload gate met AND every evaluator >= 70% */
            overall_pass: boolean | null;
        };
        PageMeta: {
            page: number;
            page_size: number;
            total: number;
        };
        EvidencePage: {
            items: components["schemas"]["Evidence"][];
            meta: components["schemas"]["PageMeta"];
        };
        MappingPage: {
            items: components["schemas"]["Mapping"][];
            meta: components["schemas"]["PageMeta"];
        };
        AssignmentPage: {
            items: components["schemas"]["Assignment"][];
            meta: components["schemas"]["PageMeta"];
        };
        Report: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            school_id: string;
            /** Format: uuid */
            cycle_id: string;
            /** Format: uuid */
            round_id?: string | null;
            /** Format: uuid */
            subject_personnel_id: string;
            template_code: components["schemas"]["ReportTemplateCode"];
            status: components["schemas"]["ReportStatus"];
            /** Format: date-time */
            generated_at: string;
        };
        ReportCreate: {
            /** Format: uuid */
            cycle_id: string;
            /**
             * Format: uuid
             * @description Optional round scope (PA2/PA3 often round-scoped)
             */
            round_id?: string | null;
            /** Format: uuid */
            subject_personnel_id: string;
            template_code: components["schemas"]["ReportTemplateCode"];
        };
        ReportSectionRef: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            report_id: string;
            /** Format: uuid */
            evidence_id?: string | null;
            /** Format: uuid */
            mapping_id?: string | null;
            section_key: string;
            sort_order: number;
        };
        ReportDetail: components["schemas"]["Report"] & {
            payload: components["schemas"]["ReportPayload"];
            section_refs: components["schemas"]["ReportSectionRef"][];
        };
        ReportPayload: {
            /**
             * @description Payload schema major version (ReportPayloadV1)
             * @constant
             */
            schema_version: 1;
            /** @enum {string} */
            generation_status: "pending" | "ready";
            template_code: components["schemas"]["ReportTemplateCode"];
            subject?: {
                /** Format: uuid */
                personnel_id: string;
                full_name: string;
                position_role: string;
                rank_level_code: string;
            };
            cycle?: {
                /** Format: uuid */
                id: string;
                title: string;
                fiscal_year: number;
                evaluation_kind: string;
                framework_code: string;
                framework_legal_ref: string;
            };
            round?: {
                /** Format: uuid */
                id: string;
                round_number: number;
                purpose: string;
                status: string;
            } | null;
            confirmed_mappings?: {
                /** Format: uuid */
                mapping_id: string;
                /** Format: uuid */
                evidence_id: string;
                evidence_title: string;
                /** Format: uuid */
                indicator_id: string;
                indicator_code: string;
                indicator_name_th: string;
                /** Format: date-time */
                confirmed_at: string | null;
            }[];
            assignments?: {
                /** Format: uuid */
                assignment_id: string;
                /** Format: uuid */
                round_id: string;
                round_number: number;
                status: string;
                committee_size: number;
                evaluator_results: {
                    /** Format: uuid */
                    evaluator_user_id: string;
                    part1_percent: number;
                    part2_percent: number;
                    total_percent: number;
                    passed_individual_threshold: boolean;
                    /** Format: date-time */
                    computed_at: string;
                }[];
            }[];
            /**
             * Format: date-time
             * @description Present when generation_status=ready
             */
            generated_at?: string;
        };
        ReportPage: {
            items: components["schemas"]["Report"][];
            meta: components["schemas"]["PageMeta"];
        };
    };
    responses: {
        /** @description AUTH-* — missing/expired/invalid credentials */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description PERM-* — role or tenancy denial */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description RES-001 — not found or cross-tenant (indistinguishable by design) */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description VAL-001 — malformed request */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description VAL/UPL/MAP/SCORE/CYCLE-* — semantically invalid */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description RES-002/MAP-001/UPL-004/CYCLE-002/SCORE-002 — state conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        FrameworkId: string;
        CycleId: string;
        RoundId: string;
        EvidenceId: string;
        AssignmentId: string;
        ReportId: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["ValidationError"];
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Revoked (idempotent — also 204 if the token was already revoked) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listFrameworks: {
        parameters: {
            query?: {
                role_family?: components["schemas"]["RoleFamily"];
                status?: "active" | "superseded" | "draft";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Framework versions (no nested taxonomy — keep list light) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Framework"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getFramework: {
        parameters: {
            query?: {
                /** @description Comma-separated expansions. `levels` adds IndicatorLevelDescription rows. */
                include?: "levels";
            };
            header?: never;
            path: {
                frameworkId: components["parameters"]["FrameworkId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Framework detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FrameworkDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listEvidenceCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories (framework-named evidence classes) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceCategory"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listCycles: {
        parameters: {
            query?: {
                fiscal_year?: number;
                evaluation_kind?: components["schemas"]["EvaluationKind"];
                status?: components["schemas"]["CycleStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cycles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cycle"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createCycle: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CycleCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cycle"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getCycle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cycle detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CycleDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCycle: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CyclePatch"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cycle"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    createRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cycleId: components["parameters"]["CycleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Round"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    updateRound: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roundId: components["parameters"]["RoundId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoundPatch"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Round"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listEvidence: {
        parameters: {
            query?: {
                owner_personnel_id?: string;
                category_id?: string;
                status?: components["schemas"]["EvidenceStatus"];
                /** @description Only evidence having an active mapping to this indicator */
                mapped_to_indicator_id?: string;
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged evidence list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidencePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidenceCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Evidence detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Soft-deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateEvidence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvidencePatch"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    initiateFileUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileUploadInitiate"];
            };
        };
        responses: {
            /** @description Upload target issued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileUploadTarget"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    completeFileUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
                fileId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FileUploadComplete"];
            };
        };
        responses: {
            /** @description File registered (scan pending) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceFile"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getEvidenceFileDownloadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
                fileId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Short-lived presigned GET URL */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FileDownloadUrl"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description File not servable (scan pending or blocked — UPL-006) */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listEvidenceMappings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mappings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mapping"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createMapping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingCreate"];
            };
        };
        responses: {
            /** @description Created (status=suggested until confirmed) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mapping"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    suggestMappings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evidenceId: components["parameters"]["EvidenceId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["MappingSuggestRequest"];
            };
        };
        responses: {
            /** @description Suggestions created (may be empty) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingSuggestResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listMappings: {
        parameters: {
            query?: {
                indicator_id?: string;
                cycle_id?: string;
                status?: components["schemas"]["MappingStatus"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged mappings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MappingPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    actOnMapping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mappingId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingAction"];
            };
        };
        responses: {
            /** @description Mapping after action */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mapping"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    listAssignments: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                roundId: components["parameters"]["RoundId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged assignments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    createAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roundId: components["parameters"]["RoundId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assignment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignmentId: components["parameters"]["AssignmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Assignment detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    submitMyScores: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignmentId: components["parameters"]["AssignmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreSubmission"];
            };
        };
        responses: {
            /** @description Stored; per-evaluator rollup returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluatorResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getAssignmentResults: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignmentId: components["parameters"]["AssignmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResults"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listReports: {
        parameters: {
            query?: {
                cycle_id?: string;
                subject_personnel_id?: string;
                status?: components["schemas"]["ReportStatus"];
                template_code?: components["schemas"]["ReportTemplateCode"];
                page?: components["parameters"]["Page"];
                page_size?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged reports */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createReport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description Draft created; generation job enqueued */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    getReport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Report detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportDetail"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    getReportPdf: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reportId: components["parameters"]["ReportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
}
